### PR TITLE
Update notebook to work with pytorch 1.0+

### PR DESCRIPTION
**Pull request by ArdalanM**
Fixed `PositionalEncoding` function:
- RuntimeError: "exp" not implemented for 'torch.LongTensor'
- replaced `0` with `0.`

Fixed warning in `xavier_uniform` initialization:

 - Warning: `nn.init.xavier_uniform` is now deprecated
 - replaced with `nn.init.xavier_uniform_`

Fixed `nn.KLDivLoss` function:
- Warning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
- replaced with `nn.KLDivLoss(reduction='sum')`

Fixed tensor casting to numpy:

- IndexError: invalid index of a 0-dim tensor
- cast Tensors to numpy arrays with .detach().numpy() or just .numpy()

### CODE REVIEW

**Comment by ArdalanM** [comment]
Solve issue #26

**Comment by srush** [comment]
Thanks this is great. I will to try to get this into the code base this week and give you credit!

**Comment by YangWang92** [comment]
Thanks for your help, it works on pytorch 1.0.1.post2.

**Comment by LawsonAbs** [comment]
these thanks comes from China.
谢谢你。
is I very naughty？

**Pull request closed without merging**
